### ISSUE TITLE
Let's get started

### ISSUE THREAD

**Issue by britta-wstnr** [meeg-cfin/introduction_to_beamforming#2]
@cjayb @sarangnemo 
I just added a first attempt on the [outline](https://github.com/meeg-cfin/introduction_to_beamforming/blob/master/Outline.md)  of the workshop - I hope this helps us getting started on brainstorming!

**Comment by cjayb** [comment]
Thanks, look really good to me. I'll work on getting working `conda` envs and associated instructions built/tested. Also have something for the forward modeling bits, general enough, though geared towards surface-based source space creation. I'll dig something up asap.

Let's work on this separately for now, meet late next week to meld together.
